### ISSUE TITLE
Миграция на систему плагинов atls/tools

### ISSUE THREAD

**Issue by TorinAsakura** [atls-academy/jumpeebunee.github.io#5]
### Какого рода задача?
Мигрировать авторизацию на tools

###  Что и где будем менять?
Для сборки приложения необходимо использовать `yarn service build`, для запуска в дев режиме - `yarn service dev`

Необходимо оформить файл auth как пакет (воркспейс) с определенной структурой: директория `src` и `index.ts` внутри - [пример](https://github.com/atls/hyperion/blob/master/ui-parts/button/package.json)

Внутри package.json должны находится скрипты для запуска проекта - `build`, `dev` и `start`

- `build` билдит проект через `yarn service build` и кладет js в папку `dist`
- `dev` запускает проект в dev режиме
- `start` запускает уже сбилженный проект (`node dist/index.js`)

[Краткий обзор tools](https://github.com/atls/tools/wiki)

### Укажите референс
Приведение проекта к общему стеку

Пример приложения, собирающегося с помощью `yarn service` - https://github.com/atls/project-starter/blob/master/gateway/entrypoints/public/package.json

Пример библиотеки, которая будет публиковаться в npm регистр - https://github.com/atls/nextjs/blob/master/packages/next-sitemap-generator/package.json

**Comment by jumpeebunee** [comment]
**Скоуп**
Запуск билда

**Описание**
Не билдится проект и выкидывает ошибку из-за bcrypt,  если убрать импорт bcrypt, то все будет билдиться  без ошибок,

**Запуск**
```sh
yarn build
```

**Логи**
```sh
webpack Module not found: Error: Can't resolve 'mock-aws-s3' in '/home
➤ YN0000: │     /jumpeebunee/.yarn/berry/cache/@mapbox-node-pre-gyp-npm-1.0.10
➤ YN0000: │     -1811160047-9.zip/node_modules/@mapbox/node-pre-gyp/lib/util'
```

**Comment by TorinAsakura** [comment]
@jumpeebunee Что это? Что мне нужно сделать? Где вопрос/запрос? Причём тут bcrypt когда ошибка ссылается на зависимости, которых тут вообще быть не должно по идее. Такое могло произойти если ты откуда-то скопипастил зависимости, которых не должно быть в проекте

**Comment by TorinAsakura** [comment]
почему у тебя ПР не привязан к задаче? По мержу ПРа должна закрываться задача
